site_name: AR. Портфолио Python

# Навигация
nav:
- Главная: index.md
- Об авторе: about.md
- Проекты:
    - 1. Cтатический сайт-портфолио на основе mkdocs: projects/project_1.md
    - 2. Проект 2: projects/project_2.md
    - 3. Проект 3: projects/project_3.md


theme:
  name: material
  palette:
    # Светлая тема (Material default)
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Переключить на тёмную тему

    # Тёмная тема (Material slate) с цветами, напоминающими Dracula
    - scheme: slate
      primary: deep purple
      accent: pink
      toggle:
        icon: material/weather-night
        name: Переключить на светлую тему

# Плагины
plugins:
  - search
  # - mkdocs_pymdownx_material_extras

